"""agentseam — the primitives layer for every coding agent."""

__version__ = "0.2.1"

from . import adapters, bundler, instructions, packaging, permissions
from .contract import (
    ALLOW,
    ASK,
    DENY,
    ESCALATE,
    EVENTS,
    FILE_CHANGED,
    INSTRUCTIONS_LOADED,
    POST_TOOL,
    PRE_COMPACT,
    PRE_TOOL,
    PROMPT_SUBMIT,
    REWRITE,
    SESSION_END,
    SESSION_START,
    STOP,
    SUBAGENT_START,
    SUBAGENT_STOP,
    TOOL_FAILURE,
    TRANSFORM,
    UNKNOWN,
    VOUCH,
    WARN,
    Decision,
    Event,
)
from .dispatch import degrade, handle, run
from .matrix import (
    MATRIX,
    adapted_agents,
    agents,
    can_block,
    can_rewrite,
    can_transform,
    capability,
    enforcement_level,
)

__all__ = [
    "ALLOW",
    "ASK",
    "DENY",
    "ESCALATE",
    "EVENTS",
    "FILE_CHANGED",
    "INSTRUCTIONS_LOADED",
    "MATRIX",
    "POST_TOOL",
    "PRE_COMPACT",
    "PRE_TOOL",
    "PROMPT_SUBMIT",
    "REWRITE",
    "SESSION_END",
    "SESSION_START",
    "STOP",
    "SUBAGENT_START",
    "SUBAGENT_STOP",
    "TOOL_FAILURE",
    "TRANSFORM",
    "UNKNOWN",
    "VOUCH",
    "WARN",
    "Decision",
    "Event",
    "__version__",
    "adapted_agents",
    "adapters",
    "agents",
    "bundler",
    "can_block",
    "can_rewrite",
    "can_transform",
    "capability",
    "degrade",
    "enforcement_level",
    "handle",
    "instructions",
    "packaging",
    "permissions",
    "run",
]
