"""agentseam — the primitives layer for every coding agent."""

__version__ = "0.1.1"

from . import adapters, bundler, instructions, packaging, permissions
from .contract import (
    ALLOW,
    ASK,
    DENY,
    EVENTS,
    FILE_CHANGED,
    INSTRUCTIONS_LOADED,
    POST_TOOL,
    PRE_COMPACT,
    PRE_TOOL,
    PROMPT_SUBMIT,
    REWRITE,
    SESSION_END,
    SESSION_START,
    STOP,
    SUBAGENT_START,
    SUBAGENT_STOP,
    TOOL_FAILURE,
    UNKNOWN,
    Decision,
    Event,
)
from .dispatch import degrade, handle, run
from .matrix import MATRIX, adapted_agents, agents, can_block, can_rewrite, capability, enforcement_level

__all__ = [
    "run",
    "handle",
    "degrade",
    "Event",
    "Decision",
    "EVENTS",
    "adapters",
    "bundler",
    "instructions",
    "packaging",
    "permissions",
    "ALLOW",
    "DENY",
    "ASK",
    "REWRITE",
    "MATRIX",
    "agents",
    "capability",
    "can_block",
    "can_rewrite",
    "enforcement_level",
    "adapted_agents",
    "SESSION_START",
    "SESSION_END",
    "PROMPT_SUBMIT",
    "PRE_TOOL",
    "POST_TOOL",
    "TOOL_FAILURE",
    "PRE_COMPACT",
    "STOP",
    "SUBAGENT_START",
    "SUBAGENT_STOP",
    "INSTRUCTIONS_LOADED",
    "FILE_CHANGED",
    "UNKNOWN",
    "__version__",
]
