"""Bundler templates: the header banner and the single-agent runtime `bundle()` composes.

Split out of `bundler.py` (which does the source-level composition) to stay under the
file-size convention -- this module owns the literal text, that one owns the assembly.
"""

from __future__ import annotations


def section(title, body):
    return "# %s\n# %s\n\n%s\n" % ("-" * 78, title, body.strip("\n") + "\n")


HEADER = """\
# Generated by agentseam {version} -- bundle("{agent}"). Do not hand-edit, except the
# HANDLER block below (between "agentseam handler >>>" and "<<< agentseam handler"),
# which is exactly what this file leaves for you to fill in.
#
# Self-contained: stdlib only, no "import agentseam" anywhere in this file. Regenerate
# with `agentseam.bundler.bundle("{agent}")` (same agentseam version -> identical bytes,
# except your own edits inside the handler block) rather than patching this by hand.
# https://github.com/open-coder-ai/agentseam
"""

RUNTIME = '''\
_VOUCH_SPEAKS = {vouch_speaks!r}
_REWRITE_EVENTS = frozenset({rewrite_events!r})


def degrade(decision, event):
    """Reduce a decision to what {agent!r} can actually honor, honestly.

    This is agentseam.dispatch.degrade(), specialized to one fixed agent so this file needs
    no "import agentseam" -- {vouch_speaks_note}.
    """
    if decision.outcome == REWRITE and event.event not in _REWRITE_EVENTS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = REWRITE
        return Decision.ask(decision.reason or "input requires modification before it can run", evidence=evidence)
    if decision.outcome == VOUCH and not _VOUCH_SPEAKS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = VOUCH
        return Decision.allow(decision.reason, evidence=evidence, context=decision.context)
    return decision


# >>> agentseam handler >>>
# Your policy goes here. `event` is a normalized Event: event.event is one of the
# canonical EVENTS strings (e.g. "pre_tool"); event.command/path/content/output/prompt
# carry whatever this event's real payload had, or None where it had nothing. Return a
# Decision (Decision.allow/deny/ask/rewrite/vouch -- all defined above) or None, which
# means an honest, unconditional allow.
def handle(event):
    raise NotImplementedError(
        "fill in your policy: replace this function body, between the "
        "'agentseam handler' markers above and below, before running this file for real"
    )
# <<< agentseam handler <<<


def _coerce(result):
    if result is None:
        return Decision.allow()
    if isinstance(result, Decision):
        return result
    raise TypeError("handle() must return a Decision or None, got %r" % (type(result),))


def _read_payload(stream):
    # Decode bytes ourselves rather than trust the platform locale -- a BOM'd or non-UTF-8
    # stdin must not silently disable the gate. See agentseam.dispatch for the incident
    # this guards: a Windows console's cp1252 layer turning a UTF-8 BOM into three bytes
    # json cannot parse, with the hook allowing everything while claiming enforcement.
    buffer = getattr(stream, "buffer", None)
    if buffer is not None:
        return buffer.read().decode("utf-8-sig", errors="replace")
    return stream.read().lstrip("\\ufeff")


def _emit(out, text):
    buffer = getattr(out, "buffer", None)
    if buffer is not None:
        buffer.write(text.encode("utf-8"))
        buffer.flush()
    else:
        out.write(text)
        out.flush()


def main(stdin=None, stdout=None, exit=True):
    """Read one payload from stdin, dispatch, emit the {agent!r} response, exit."""
    stream = stdin if stdin is not None else sys.stdin
    out = stdout if stdout is not None else sys.stdout
    try:
        raw = json.loads(_read_payload(stream))
    except Exception:
        # Malformed input is not the agent's fault to pay for: allow, stay silent.
        if exit:
            sys.exit(0)
        return 0
    event = parse(raw)
    if event.event == UNKNOWN:
        # A vendor event this adapter has no mapping for. handle() is not called: it
        # reasons about the canonical vocabulary, and handing it something outside that
        # vocabulary invites a decision made on a false premise.
        if exit:
            sys.exit(0)
        return 0
    decision = degrade(_coerce(handle(event)), event)
    text, code = respond(decision, event)
    if text:
        _emit(out, text)
    if exit:
        sys.exit(code)
    return code


if __name__ == "__main__":  # pragma: no cover
    main()
'''
