"""The shape of a submitted evidence report, and the rules it must satisfy.

Evidence is going to arrive from strangers -- that is the point of the capture kit, and
the only model that keeps sixteen rows honest without a maintainer buying sixteen seats.
Strangers submitting JSON means the schema is a trust boundary, so it lives in the runtime
where CI, the CLI and a contributor's own machine all read the identical rules.

The rules are deliberately about *provenance*, not about whether a measurement is
plausible. A report claiming Cursor fails open when the matrix says otherwise is exactly
the report worth having; rejecting surprising results would make this a device for
confirming what is already believed. What must never pass is a report that overstates how
it was obtained.

Hence the invariant this module exists for:

    A report produced by the reference driver may never claim `live-run`.

The reference driver is the vendor's documentation, made executable. It is useful and it
is not a measurement, and the difference is the whole distinction the matrix rests on. A
run against it that laundered itself into a `live-run` row would quietly convert twelve
documentation guesses into twelve apparent measurements.
"""

from __future__ import annotations

from .matrix_terms import BASES, BASIS_DOCS, BASIS_LIVE, BASIS_LIVE_PARTIAL

#: Current report format. Bumped when a required field changes, so an old submission is
#: rejected with "regenerate this" rather than silently half-read.
REPORT_VERSION = 1

REQUIRED = ("report_version", "agent", "basis", "date", "driver")

#: Fields a submitter may set but that carry no authority: they describe the run, and a
#: maintainer weighs them. Listed so an unknown key is a typo rather than a shrug.
OPTIONAL = (
    "version",
    "reporter",
    "platform",
    "agent_build",
    "measurements",
    "observed",
    "experiments",
    "run_url",
    "notes",
    "tool_version",
)

#: The driver name the harness uses for its credential-free documentation simulator.
REFERENCE_DRIVER = "reference"

#: Bases that assert somebody watched a real agent do something.
LIVE_BASES = (BASIS_LIVE, BASIS_LIVE_PARTIAL)


class InvalidReportError(ValueError):
    """A submitted report cannot be trusted as what it says it is."""


def _missing(report):
    # Presence, not truthiness: `report_version: 0` is a *stale* report, not an absent
    # field, and telling a contributor "you forgot this" when they sent it is how a
    # fixable submission gets abandoned.
    return [key for key in REQUIRED if key not in report or report[key] in (None, "")]


def _unknown(report):
    allowed = set(REQUIRED) | set(OPTIONAL)
    return sorted(set(report) - allowed)


def validate(report):
    """Raise InvalidReportError unless `report` is a well-formed, honestly-labelled submission.

    Returns the report unchanged so callers can chain. Every message names the field, so a
    contributor can fix a submission without reading this file.
    """
    if not isinstance(report, dict):
        raise InvalidReportError("a report must be a JSON object, got %s" % type(report).__name__)

    missing = _missing(report)
    if missing:
        raise InvalidReportError("missing required field(s): %s" % ", ".join(missing))

    unknown = _unknown(report)
    if unknown:
        raise InvalidReportError("unknown field(s): %s -- typo, or generated by a newer tool?" % ", ".join(unknown))

    if report["report_version"] != REPORT_VERSION:
        raise InvalidReportError(
            "report_version %r; this repository reads %d. Regenerate with the current tool."
            % (report["report_version"], REPORT_VERSION)
        )

    if report["basis"] not in BASES:
        raise InvalidReportError("basis %r is not one of: %s" % (report["basis"], ", ".join(BASES)))

    # The invariant this module exists for.
    if report["driver"] == REFERENCE_DRIVER and report["basis"] in LIVE_BASES:
        raise InvalidReportError(
            "a run against the %r driver cannot claim basis %r: that driver is the vendor's "
            "documentation made executable, not a running agent. Use %r, or re-run against "
            "the real agent." % (REFERENCE_DRIVER, report["basis"], BASIS_DOCS)
        )

    if report["basis"] in LIVE_BASES and not report.get("version"):
        raise InvalidReportError(
            "basis %r requires `version`: evidence that does not say which build it "
            "watched cannot be checked for drift later." % report["basis"]
        )

    if not str(report["date"]).count("-") == 2:  # noqa: PLR2004
        raise InvalidReportError("date must be YYYY-MM-DD, got %r" % (report["date"],))

    return report


def to_evidence(report):
    """The matrix-evidence.json entry a validated report becomes.

    Kept separate from validate() because merging is a maintainer's act: this returns what
    the row *would* say, for review, and writes nothing.
    """
    validate(report)
    entry = {
        "basis": report["basis"],
        "date": report["date"],
        "version": report.get("version") or "unrecorded",
        "method": report.get("notes") or "submitted evidence report",
    }
    for key in ("observed", "experiments", "reporter", "run_url"):
        if report.get(key):
            entry[key] = report[key]
    return entry


def diff_against(existing, report):
    """Which fields a submission would change on an existing row, for review.

    Nothing is written. A submission that would *weaken* a row -- replacing a live-run with
    documentation -- is surfaced explicitly, because that is the change most likely to be
    an accident and least likely to be noticed in a diff.
    """
    proposed = to_evidence(report)
    changes = {k: (existing.get(k), v) for k, v in proposed.items() if existing.get(k) != v}
    weakens = existing.get("basis") in LIVE_BASES and proposed["basis"] not in LIVE_BASES
    return {"changes": changes, "weakens_basis": weakens}
