"""The caveats each matrix row carries, kept apart from the capabilities it declares.

Two different activities. A row's `events` table is a set of capability tuples that a
consumer queries; its note is prose telling a human what to watch out for -- which surface
is missing, which decision word the vendor accepts but does not honour, what fails open.
The prose is the part that grows, and it grows every time a vendor is read properly.
"""

from __future__ import annotations

NOTES = {
    "junie": "Strongest gate here: PreToolUse returns allow/ask/block and carries "
    "updatedInput, so block, ask and rewrite are all native. Its event names and field "
    "names are Claude Code's by design; project_path is what separates the two payloads. "
    "Project-local hooks in <project>/.junie/config.json are IGNORED by default for "
    "safety, so a guardrail committed to a repo does not run for a teammate who clones it "
    "-- the user file is the only location that takes effect without --config-location. "
    "PermissionRequest inverts the usual default: a hook exiting 0 without a blocking "
    "decision approves the action and skips the dialog the user would have seen. Deliberately "
    "not installable on its own -- it shares canonical pre_tool with PreToolUse, and "
    "install('junie', ['pre_tool']) wires only PreToolUse, since bundling the two would hand "
    "a consumer an approve-by-default gate they did not ask for. Wire it by hand if wanted. "
    "StopFailure is observability-only and fires on LLM/API failures, not tool failures, "
    "so it is not tool_failure and is left unmapped. Non-zero exits other than 2 are "
    "warnings and execution proceeds, so this fails OPEN.",
    "tabnine": "Eleven events, six of which can block -- including AfterTool, which most "
    "agents treat as observation only. Event names are Gemini CLI's exactly; the only "
    "documented separator is `timestamp` in Tabnine's base schema, which identifies "
    "Tabnine but cannot exclude Gemini, so detect() declines these payloads and the agent "
    "must be named explicitly. Fails OPEN unusually broadly: any exit code other than 0 "
    "or 2 proceeds, AND stdout that is not valid JSON is treated as a systemMessage and "
    "the action is ALLOWED -- so a chatty or crashed hook is a permitted action. Rewrite "
    "is advertised in the vendor overview but the field carrying it was not in the "
    "documentation read here, so no rewrite is claimed.",
    "replit": "No hook surface found in the vendor documentation. Recorded as not-found "
    "rather than absent: this is a hosted agent, and the search was of published docs, not "
    "of a running instance. Instruction files still reach it.",
    "antigravity": "Richest decision vocabulary here -- allow, deny, ask, force_ask and deny_unless_prior_grant -- but no rewrite, since permissionOverrides widens permissions rather than changing arguments. The payload carries NO event name, so the event is inferred from shape, and PreToolUse/PostToolUse differ only by an `error` field documented as empty rather than absent; ties go to PreToolUse because the opposite guess would skip the gate. PreInvocation and PostInvocation have identical payloads and are unmapped. Fail mode is not documented, so the weaker claim (open) is recorded rather than a guess in our own favour.",
    "claude_code": "Richest surface (~30 events). Blocks via exit 2 or hookSpecificOutput.permissionDecision; rewrite via updatedInput (pre_tool only). Fail mode is not documented anywhere in this project (notes, docstring, evidence, CHANGELOG) for pre_tool or prompt_submit, so the weaker claim (FAIL_OPEN) is recorded rather than a guess in our own favour -- pre_tool and prompt_submit had rested on FAIL_CLOSED with no basis, the strongest claim in the whole vocabulary, and the only one of its kind unsupported here. PreCompact's block=True was similarly unsupported and is now detect-only; the hooks reference at the time this adapter was written suggests PreCompact's exit 2 writes to stderr without blocking anything. Live capture 2026-08-27 found detection broken against current builds: Claude Code now sends prompt_id, which this adapter treated as proof a payload was Devin's, so 38 of 42 real payloads were claimed by Devin instead and a deny rendered in the wrong dialect. Fixed by discriminating on fields observed from Claude Code rather than on a field it was assumed to lack. A second live round (2.1.247, 2026-08-28) settled the RESPONSE contract, which no capture can show: each event was sent one candidate reply shape per trial and the verdict read off the agent's own behaviour. prompt_submit and stop read a TOP-LEVEL {decision: block, reason} and ignore hookSpecificOutput.permissionDecision outright -- the shape this adapter emitted at every event, so every prompt_submit and stop deny it ever produced was silently discarded while the dispatcher reported a block. exit 2 is honoured at both too and is deliberately not used: it collapses to 1 under the PowerShell wrapper some vendors apply, and it leaks the hook's command line into the UI. pre_tool keeps permissionDecision, which was not part of that experiment; the observation-only events now get silence.",
    "codex_cli": "Claude-family decision shape (hookSpecificOutput.permissionDecision) and Claude-family PascalCase event names (verified against hook_config.rs/schema.rs; an earlier version of this note wrongly said camelCase, sourced from the App Server's separate IDE-facing protocol rather than the CLI hook dialect this adapter speaks). Told apart from Claude Code by turn_id: permission_mode and model were also believed exclusive to Codex and turned out not to be -- a real live-captured Claude Code payload carries permission_mode too, and model cannot discriminate either since Cursor's base hook schema also sends it on every event -- so turn_id is the only one of the three still unrefuted by a real payload. Deny is sent as JSON with exit 0: on Windows Codex wraps hooks in powershell -Command, which collapses exit 2 into 1, so an exit-code deny does not survive that platform. That same PowerShell wrapper will not RUN a command line beginning with a quoted path -- it parses as a string expression, not an invocation -- so installs emit Codex's own commandWindows override carrying the `&` call operator (witnessed live 2026-08-28: without it every hook failed with exit 1 and never executed). Three response dialects, one per event group, because every per-event output struct is deny_unknown_fields and rejects the whole response over a foreign key: pre_tool takes hookSpecificOutput.permissionDecision, prompt_submit and stop take a top-level {decision: block, reason}, and the observation-only events accept no verdict at all and get silence. A bare allow is silence everywhere -- permissionDecision:allow is rejected unless it carries updatedInput, and a rejected response fails OPEN. ask is likewise unsupported and degrades to a deny with an explanatory reason. Live capture 2026-08-28 (36 payloads) settled the write vocabulary: Codex sends exactly two tool names, Bash and apply_patch, and BOTH carry only tool_input.command -- apply_patch is the file-writing tool and the patch rides in that string, so event.path and event.content are None on a real write and a content policy has to gate on event.command. The file_path/content/new_string/edits vocabulary previously read here was Claude Code's, copied over on an assumption, and no Codex payload has ever carried it. The same capture showed SessionStart carries no turn_id (it is not turn-scoped) and nothing else separates it from Claude Code's, so detect() now declines on it rather than answering in the wrong dialect.",
    "cursor": "Fails OPEN by default; failClosed:true per hook definition makes it fail closed, and agentseam sets it on every gate it installs. `ask` is accepted by the preToolUse schema but not enforced today, so the adapter denies instead of returning a prompt that would behave as a pass; beforeShellExecution and beforeMCPExecution do honour ask. Separate Tab hooks (beforeTabFileRead, afterTabFileEdit) gate inline completions, and workspaceOpen fires outside any session with no canonical event here. Cursor also loads Claude Code-format hooks -- confirmed live (2026-08-27): with both `.cursor/hooks.json` and `.claude/settings.json` carrying the same probe, every event fired twice, once per config. Witnessed live (Windows, 2026-08-27): a beforeShellExecution hook that produced no stdout caused the tool call to be REJECTED -- an empty response is not an allow, so silence blocks and the documented fail-open covers something narrower than any-hook-problem. A hook wired here must answer in-dialect. Across three capture sessions in which shell commands ran, beforeShellExecution never fired while tool_input.command arrived under preToolUse instead -- non-observation, not evidence of absence, but enough that a consumer should gate shell on pre_tool rather than assume the dedicated event.",
    "devin": 'Speaks Claude Code\'s hook format almost exactly, and reads .claude/settings.json for hooks by default -- so a repo with Claude Code hooks is already running them under Devin. A block is top-level {"decision": "block"}, not permissionDecision. There is no ask in the vocabulary. Non-zero exit codes other than 2 are logged without blocking, so this fails OPEN. A SessionStart payload is indistinguishable from Claude Code\'s, and detect() refuses to guess between them.',
    "gemini_cli": "Top-level `decision: allow|deny|ask` + `reason` (not nested); rewrite merges via hookSpecificOutput.tool_input; exit 2 also blocks. Write tools are write_file/replace. Fail mode is not documented as closed, so pre_tool is rated best-effort rather than enforced. Source (read from a clone, 2026-08-28) corrected two things the hooks reference alone had settled wrongly. `ask` IS honoured, at BeforeTool only: hook-utils routes isAskDecision() to PolicyDecision.ASK_USER and calls resolveConfirmation with forcedDecision:'ask_user', which prompts even where the user's own policy rule would have auto-allowed -- a stronger ask than most vendors here can express, and this adapter was degrading it to a deny. At BeforeAgent/AfterAgent only isBlockingDecision() is consulted, so an ask there is inert and the degradation is right. Conversely `allow` is read NOWHERE: nothing in the tree tests for it and hookAggregator synthesises it when no hook objected, so unlike VS Code's permissionDecision:allow it cannot skip a confirmation.",
    "grok": "PreToolUse is the ONLY blocking event; everywhere else stdout is ignored. No rewrite: the vocabulary is {decision: deny, reason} and nothing more. Fails OPEN -- timeouts, crashes and malformed output are recorded and the call proceeds. Payload fields are camelCase (hookEventName, toolName) while event values stay PascalCase, which is what separates it from Claude Code, Codex and VS Code Copilot. Reads .claude/settings.json and .cursor/hooks.json too. Project hooks need trust (/hooks-trust or --trust) before they run, so a written config is not yet a live one.",
    "kimi_code": "Twenty events, of which exactly three block: PreToolUse, UserPromptSubmit and Stop. The rest are documented as fire-and-forget, so a decision returned there changes nothing. Accepts Claude Code's hookSpecificOutput.permissionDecision shape, and exit 2 blocks too -- but the JSON form carries the reason back into the model's context. No rewrite. Config is TOML ([[hooks]] in config.toml, four fields only; a fifth makes the whole file fail to load), so installation appends a marker-delimited block rather than rewriting the user's settings. Fails OPEN, and the vendor says outright that hooks here are not a sole security barrier. Only client_type separates its payloads from Claude Code's.",
    "vscode_copilot": "Two products behind one row, and they do not spell events the same way: HOOKS_BY_TARGET gives VS Code agent mode PascalCase names (Claude Code's exactly) and the GitHub Copilot CLI camelCase ones (sessionStart, userPromptSubmitted, agentStop). This adapter claimed camelCase only until 2026-08-28, so it never claimed a real VS Code payload at all -- those went to claude_code alone and were answered in its dialect, which is right at PreToolUse and wrong everywhere else. `timestamp`, which chatHookService merges into every payload, is what separates the two; Tabnine sends it too, so SessionStart -- the one event name Tabnine and VS Code share -- is left ambiguous rather than guessed. `postToolUseFailure`, previously mapped, claimed and installed for, is in neither vendor's name map: it never existed. Four response dialects, because the consumer reads a different shape at each: PreToolUse takes hookSpecificOutput.permissionDecision (ask and updatedInput both native, and updatedInput is validated against the tool's schema and silently discarded if it fails), UserPromptSubmit and PostToolUse take a top-level {decision: block, reason}, Stop and SubagentStop take those two fields nested in hookSpecificOutput and drop the block if the reason is missing, and SessionStart/SubagentStart run under ignoreErrors:true where even exit 2 is swallowed. hookEventName is echoed rather than hardcoded: _toHookResult strips hookSpecificOutput outright when the name does not match the event being run. Fails OPEN, not closed as this row claimed for two weeks: exit 2 blocks, but any other non-zero exit is a NonBlockingError that warns the user and lets the call proceed. Also parses Claude settings.json via hookClaudeCompat, and ignores `matcher` -- it is read and thrown away, so there is no tool filtering and the guard must check event.tool itself. Memory writes arrive as the 'memory' tool (create/str_replace/insert), not file edits.",
    "windsurf": "Exit code 2 is the ONLY block signal: no stdout decision protocol, no machine-readable reason, no rewrite. Critically there is NO file-write event -- prompt, terminal and MCP hooks only -- so a write to a memory file is invisible to a hook on this agent. Fail mode is undocumented, so blocking rates best-effort rather than enforced.",
}
