#!/usr/bin/env python3
"""Generate `examples/generated/` -- one page per agent, showing what agentseam produces.

Nothing here is written by hand. Every config fragment and every response on those pages
comes out of the real code paths, so the pages cannot describe behaviour the library does
not have. `tests/test_examples.py` regenerates them and fails if the committed files differ,
which turns the examples into a claim CI checks rather than documentation that rots.

    python3 examples/generate.py [--check]

`--check` reports drift without writing, which is what CI runs.
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.insert(0, os.path.dirname(__file__))

from scenarios import SCENARIOS  # noqa: E402

import agentseam as A  # noqa: E402
from agentseam import Decision, adapters, packaging, permissions  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "generated")

#: The decisions each page walks through, in the order a reader meets them.
DECISIONS = [
    ("allow", lambda: Decision.allow(), "the handler is happy"),
    ("deny", lambda: Decision.deny("secret detected in file content"), "the handler refuses"),
    ("ask", lambda: Decision.ask("looks like a credential -- confirm?"), "the handler wants a human"),
    (
        "rewrite",
        lambda: Decision.rewrite({"content": "AWS_SECRET_ACCESS_KEY=<redacted>"}, "redacting the secret"),
        "the handler wants the input changed",
    ),
]


def _fence(text, lang=""):
    return "```%s\n%s\n```" % (lang, text.rstrip("\n"))


def _json(obj):
    return json.dumps(obj, indent=2, sort_keys=True)


def _decision_rows(agent, raw):
    """Run each decision through the real dispatcher and record what came back."""
    rows = []
    for name, make, why in DECISIONS:
        text, code, _event, final = A.handle(raw, lambda _e, _m=make: _m(), agent=agent)
        note = ""
        if final.outcome != name:
            note = "reduced to `%s` by the dispatcher: this agent cannot %s" % (final.outcome, name)
        rows.append((name, why, text, code, note, final))
    return rows


def _page(agent):
    row = A.MATRIX[agent]
    raw = SCENARIOS[agent]
    mod = adapters.get(agent)
    event = mod.parse(raw)
    out = []
    add = out.append

    add("# %s\n" % row["display"])
    add("> Generated by `examples/generate.py`. Do not edit by hand.\n")
    add(
        "Every block below is produced by running agentseam, so it is what this agent\n"
        "actually gets -- not an illustration of what it might get.\n"
    )

    add("## What agentseam claims about it\n")
    add("| | |")
    add("|---|---|")
    add("| tier | `%s` |" % row["tier"])
    add("| enforcement at `pre_tool` | **%s** |" % A.enforcement_level(agent, A.PRE_TOOL))
    add("| can block | %s |" % ("yes" if A.can_block(agent, A.PRE_TOOL) else "no"))
    add("| can rewrite | %s |" % ("yes" if A.can_rewrite(agent, A.PRE_TOOL) else "no"))
    add("| hook config | `%s` |" % row["config"])
    add("| verified | %s (%s) |" % (row["verified"]["date"], row["verified"]["method"]))
    add("")
    add("%s\n" % row["notes"])

    add("## 1. What `agentseam install` writes\n")
    add(
        "Wiring one handler for the pre-tool gate. agentseam owns only the entries it adds;\n"
        "an uninstall removes exactly those and leaves anything else in the file alone.\n"
    )
    config = mod.hook_config([A.PRE_TOOL], "python3 guard.py")
    if getattr(mod, "CONFIG_FORMAT", "json") == "toml":
        add("`%s`\n" % mod.CONFIG_PATH)
        add(_fence(mod.render_config(config), "toml"))
    else:
        add("`%s`\n" % mod.CONFIG_PATH)
        add(_fence(_json(config), "json"))
    add("")

    add("## 2. The event the handler sees\n")
    add("The same situation for every agent: **a secret about to be written to a file.**\n")
    add("This agent sends:\n")
    add(_fence(_json(raw), "json"))
    add("\nwhich agentseam normalizes to:\n")
    add(
        _fence(
            "event    = %s\ntool     = %s\npath     = %s\ncommand  = %s\ncontent  = %s"
            % (event.event, event.tool, event.path, event.command, (event.content or "")[:48] or None)
        )
    )
    add("")

    add("## 3. What each decision looks like coming back\n")
    for name, why, text, code, note, final in _decision_rows(agent, raw):
        add("### `Decision.%s()` -- %s\n" % (name, why))
        if note:
            add("> %s\n" % note)
        if text:
            add(_fence(text, "json" if text.lstrip().startswith(("{", "[")) else ""))
        else:
            add("_No output. Exit code alone carries the answer here._")
        add("\nExit code: `%d`\n" % code)
    return "\n".join(out)


def _primitive_section(agent):
    """Permissions and packaging for one agent, or the reason there is nothing to show."""
    out = ["## 4. Other primitives\n"]
    try:
        plan = permissions.plan(agent, [permissions.Rule("deny", "shell", "curl *")])
        out.append("**Permissions** -- `deny shell curl *` rendered into `%s`:\n" % plan.path)
        body = plan.fragment
        out.append(_fence(body if isinstance(body, str) else _json(body), "" if isinstance(body, str) else "json"))
        for gap in plan.unrepresentable:
            out.append("\n> Not representable here: %s\n" % gap.reason)
    except KeyError:
        out.append("**Permissions** -- no model recorded: %s\n" % permissions.UNRECORDED[agent])

    try:
        bundle = packaging.Bundle("secrets-guard", description="Keeps secrets out of memory files")
        bundle.parts.append(packaging.Part(packaging.SKILL, "secret-scan", "# Secret scan\n"))
        laid = packaging.plan(agent, bundle)
        out.append("\n**Packaging** -- a one-skill bundle, rooted at `%s`:\n" % laid.root)
        out.append(_fence("\n".join(sorted(laid.files))))
    except KeyError:
        out.append("\n**Packaging** -- no format recorded: %s\n" % packaging.UNRECORDED[agent])
    return "\n".join(out)


def _index():
    out = ["# Generated vendor examples\n"]
    out.append("> Generated by `examples/generate.py`. Do not edit by hand.\n")
    out.append(
        "One page per agent agentseam can hook, each showing the **same situation** -- an\n"
        "agent about to write a secret into a file it will read back later -- in that\n"
        "vendor's own dialect. Every block on those pages is real output, and CI fails if\n"
        "they drift from what the library actually produces.\n"
    )
    out.append("| agent | enforcement | block | rewrite | config |")
    out.append("|---|---|---|---|---|")
    for agent in sorted(SCENARIOS):
        row = A.MATRIX[agent]
        out.append(
            "| [%s](%s.md) | %s | %s | %s | `%s` |"
            % (
                row["display"],
                agent,
                A.enforcement_level(agent, A.PRE_TOOL),
                "yes" if A.can_block(agent, A.PRE_TOOL) else "no",
                "yes" if A.can_rewrite(agent, A.PRE_TOOL) else "no",
                row["config"],
            )
        )
    out.append(
        "\nAgents with no page are not omissions. Aider and Zed expose no hook surface at\n"
        "all, and Junie, Replit and Tabnine have no adapter here yet -- `agentseam agents`\n"
        "lists every one of them with the reason.\n"
    )
    return "\n".join(out)


def build():
    """agent -> file contents. Pure, so `--check` and the test can compare without writing."""
    files = {"README.md": _index() + "\n"}
    for agent in sorted(SCENARIOS):
        files["%s.md" % agent] = _page(agent) + "\n" + _primitive_section(agent) + "\n"
    return files


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    files = build()
    if "--check" in argv:
        drift = []
        for name, body in sorted(files.items()):
            path = os.path.join(OUT, name)
            current = open(path).read() if os.path.exists(path) else None
            if current != body:
                drift.append(name)
        if drift:
            sys.stderr.write("examples are stale, run examples/generate.py: %s\n" % ", ".join(drift))
            return 1
        print("examples up to date (%d files)" % len(files))
        return 0
    os.makedirs(OUT, exist_ok=True)
    for name, body in sorted(files.items()):
        with open(os.path.join(OUT, name), "w") as fh:
            fh.write(body)
    print("wrote %d files to %s" % (len(files), OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
